export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const ES_OPERADOR = 'ES_OPERADOR';
export const ES_SUPERVISOR = 'ES_SUPERVISOR';
export const ES_INVITADO = 'ES_INVITADO';
export const OBTENER_MODELOS_BY_ID = 'OBTENER_MODELOS_BY_ID ';