export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESSION';
export const ES_VENDEDOR = 'ES_VENDEDOR';
export const ES_CLIENTE = 'ES_CLIENTE';
export const OBTENER_MODELOS_BY_ID = 'OBTENER_MODELOS_BY_ID ';
export const OBTENER_USUARIO_TIPOS = 'OBTENER_USUARIO_TIPOS';

export const MOSTRAR_FORM_USUARIO = 'MOSTRAR_FORM_USUARIO';
export const MOSTRAR_FORM_PEDIDO = 'MOSTRAR_FORM_PEDIDO';
export const MOSTRAR_LISTADO_PEDIDO = 'MOSTRAR_LISTADO_PEDIDO';